image: guix 
oauth: pages.sr.ht/PAGES:RW
sources:
  - git+https://git@git.sr.ht/~filiplajszczak/filip-lajszczak-dev
environment:
  site: filip.lajszczak.dev
tasks:
- guix: |
    guix pull
- shell: |
    cd filip-lajszczak-dev
    guix shell -L .guix -m .guix/build-manifest.scm -- ./publish.sh